name: joura_pothole
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  dots_indicator: ^4.0.1
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/auth/
    - assets/svg_icons/
